spring:
    datasource:
        username: ${HYPERPROF_DB_USER}
        password: ${HYPERPROF_DB_PASSWORD}
        url: jdbc:mysql://${HYPERPROF_DB_HOST}:${HYPERPROF_DB_PORT}/${HYPERPROF_DB_NAME}?serverTimezone=UTC
    jpa:
        show-sql: false
        properties:
            "[format_sql]": false
br:
    com:
        joaogosmani:
            hyperprof:
                core:
                    services:
                        token:
                            jjwt:
                                accessTokenSigingKey: ${HYPERPROF_JJWT_ACCESS_TOKEN_SIGING_KEY}
                                accessTokenExpirationInSeconds: ${HYPERPROF_JJWT_ACCESS_TOKEN_EXPIRATION_IN_SECONDS}
                                refreshTokenSigingKey: ${HYPERPROF_JJWT_REFRESH_TOKEN_SIGING_KEY}
                                refreshTokenExpirationInSeconds: ${HYPERPROF_JJWT_REFRESH_TOKEN_EXPIRATION_IN_SECONDS}